-- Fix function search_path security warnings
CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN AS $$ BEGIN RETURN EXISTS (SELECT 1 FROM users WHERE discord_id = current_setting('request.jwt.claims', true)::json->>'sub' AND is_admin = true); EXCEPTION WHEN OTHERS THEN RETURN false; END; $$ LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public;

CREATE OR REPLACE FUNCTION get_user_balance(p_user_id TEXT) RETURNS INTEGER AS $$ DECLARE balance INTEGER; BEGIN SELECT COALESCE(SUM(amount), 0) INTO balance FROM coin_transactions WHERE user_id = p_user_id; RETURN GREATEST(balance, 0); END; $$ LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public;

CREATE OR REPLACE FUNCTION add_coins(p_user_id TEXT, p_amount INTEGER, p_type TEXT, p_description TEXT DEFAULT NULL, p_reference_id TEXT DEFAULT NULL) RETURNS JSONB AS $$ DECLARE new_balance INTEGER; transaction_id UUID; BEGIN IF p_amount = 0 THEN RETURN jsonb_build_object('success', false, 'error', 'Amount cannot be zero'); END IF; INSERT INTO coin_transactions (user_id, amount, type, description, reference_id) VALUES (p_user_id, p_amount, p_type, p_description, p_reference_id) RETURNING id INTO transaction_id; new_balance := get_user_balance(p_user_id); UPDATE users SET coins = new_balance, updated_at = NOW() WHERE discord_id = p_user_id; RETURN jsonb_build_object('success', true, 'transaction_id', transaction_id, 'new_balance', new_balance); END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION can_claim_daily(p_user_id TEXT, p_claim_type TEXT) RETURNS BOOLEAN AS $$ BEGIN RETURN NOT EXISTS (SELECT 1 FROM daily_claims WHERE user_id = p_user_id AND claim_type = p_claim_type AND claim_date = CURRENT_DATE); END; $$ LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path = public;

CREATE OR REPLACE FUNCTION claim_daily_reward(p_user_id TEXT, p_claim_type TEXT, p_amount INTEGER DEFAULT 100) RETURNS JSONB AS $$ DECLARE can_claim BOOLEAN; result JSONB; BEGIN can_claim := can_claim_daily(p_user_id, p_claim_type); IF NOT can_claim THEN RETURN jsonb_build_object('success', false, 'error', 'Already claimed today'); END IF; INSERT INTO daily_claims (user_id, claim_type) VALUES (p_user_id, p_claim_type); IF p_claim_type = 'coins' THEN result := add_coins(p_user_id, p_amount, 'daily', 'Daily coins reward'); ELSIF p_claim_type = 'spin' THEN INSERT INTO spin_wheel_tickets (user_id, ticket_type) VALUES (p_user_id, 'daily'); result := jsonb_build_object('success', true, 'message', 'Daily spin ticket claimed'); END IF; RETURN result; END; $$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

SELECT 'Functions updated with secure search_path!' as status;
